### ISSUE TITLE
Maybe add the length of the key file for the KZW file format.

### ISSUE THREAD

**Issue by Kitsumi** [Flipnote-Collective/flipnote-studio-3d-docs#2]
I've been trying to grab the key file from a memdump I made, but I can't get the actual key full key, I've tried a few bytes more then I thought I needed, and a few less, either way it doesn't match the SHA-256. I have a key that reads in OpenSSL but doesn't let me digest files, so I'm not sure if I have the whole file, or if maybe its wrong? I made the memdump using V1.0.1 of Flipnote Studio 3D if that helps. If at all possible, maybe add the memory offset as well, if its static.

**Comment by JoshuaDoes** [comment]
Hi there!

The resulting private key should be a DER private key with a length of 294 bytes, beginning with the bytes `0x30`, `0x82`, and `0x01` and ending with the bytes `0x01`, `0x00`, and `0x01`. A SHA-256 hash over the DER private key should read out as `E6892FF794E8A768C9ECC76152C4E72823514366B3A206298F5CB603D5EB797A`.

I do not believe the memory offset would be static, as the Nintendo 3DS uses ASLR wherever possible. Otherwise I'm sure we'd have written it in the wiki. :P 

If you have any further questions, do let us know! I'll close this issue soon either if you respond with a success or no response is made. Have a good day!

**Comment by jaames** [comment]
Even without ASLR, the memory offset won't be static, it can vary depending on region, version, etc.

**Comment by Kitsumi** [comment]
It does actually seem to be static, as I've done a few different memory dumps using Luma3DS, and going to the code "tab" and pressing select, the offset seems to stay the same, since its the actual code.

**Comment by JoshuaDoes** [comment]
Even then, the only thing that's universal across versions and regions is the private key itself. Providing an offset for every single version and region of the app would be quite tedious so it's easier to leave finding it up to the user

**Comment by Kitsumi** [comment]
Thats fair, I also can't find anywhere in memory thats 294 Bytes long, starting with 30 82 01 and ending with 01 00 01. I also wrote a small program that went through large blocks of memory and checked the SHA-256 on it, and looking for a match whilst subtracting a byte one at a time, and it came up empty...

**Comment by JoshuaDoes** [comment]
Oh I made a mistake, appears I was looking at the public key derived from the private key. One moment while I look into it

**Comment by JoshuaDoes** [comment]
Alright so I found my mistake and managed to get the DER private key again. Beginning bytes should be `30 82 04` and ending bytes should be `E4 07 50`. The SHA-256 hash specified above should match this. Full size of my DER private key was equal to 1,218 bytes.

**Comment by jaames** [comment]
I can confirm, the documentation is now fixed. The hash there was already correct.

Thanks for the heads-up!

**Comment by Kitsumi** [comment]
When trying to use this key with OpenSSL I get an error though.
`$ openssl x509 -text -inform der -in test1.der -out test1.pem`
`unable to load certificate`
`1619636256:error:0D0680A8:asn1 encoding routines:ASN1_CHECK_TLEN:wrong tag:tasn_dec.c:1320:`
`1619636256:error:0D07803A:asn1 encoding routines:ASN1_ITEM_EX_D2I:nested asn1 error:tasn_dec.c:382:Type=X509_CINF`
`1619636256:error:0D08303A:asn1 encoding routines:ASN1_TEMPLATE_NOEXP_D2I:nested asn1 error:tasn_dec.c:752:Field=cert_info, Type=X509`

It does match the SHA-256, but it can't be used to digest files for signature hashing?

**Comment by jaames** [comment]
You'll want to convert it as an RSA key:
```bash
openssl rsa -inform DER -outform PEM -in key.der -out key.pem
```

**Comment by Kitsumi** [comment]
Ah! Thanks so much! I forgot that it was an RSA key.
